import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export async function generateStaticParams() {
	return [{ lang: 'en' }, { lang: 'ru' }]
}

export default function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode
	params: {
		lang: string
	}
}) {
	return (
		<html lang={params.lang}>
			<body className={inter.className}>{children}</body>
		</html>
	)
}
